name: MyFirstWorkflow
on: push
jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Creating a report file
        run: echo "This is my first GitHub Actions workflow!" > report.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: report.txt


  check_artifact:
    runs-on: self-hosted
    needs: my_first_job
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          name: report.txt

      - name: Check artifact content
        run: cat report.txt
