name: MyFirstWorkflow
on: push
jobs:
  my_first_job:
    runs-on: self-hosted
    steps:
      - name: Clone Repo
        uses: actions/checkout@v6

      - name: list files
        run: |
              ls -la
              

  my_Second_job:
    runs-on: ubuntu-latest
    needs: my_first_job
    steps:
      - name: Install nodejs
        uses: actions/setup-node@v6
        with:
          node-version: '20'

      - name: Check node js version
        run: node --version
         



